uploads = []
generated = []

[[outputs]]
id = "FYynlqm5lsRi9hHhQ8tOO"
uri = "file://godsapp-v0.3.0.tar.gz"
type = "unspecified"
title = "GodsApp v0.3.0 — tarball (fixed installer)"

[[outputs]]
id = "lm-WjXXkd3G5S6vGLDUib"
uri = "file://godsapp-v0.3.0.zip"
type = "unspecified"
title = "GodsApp v0.3.0 — ZIP (fixed installer)"
