uploads = []
generated = []

[[outputs]]
id = "FYynlqm5lsRi9hHhQ8tOO"
uri = "file://godsapp-v0.3.0.tar.gz"
type = "unspecified"
title = "GodsApp v0.3.0 — tarball (fixed installer)"

[[outputs]]
id = "lm-WjXXkd3G5S6vGLDUib"
uri = "file://godsapp-v0.3.0.zip"
type = "unspecified"
title = "GodsApp v0.3.0 — ZIP (fixed installer)"

[[outputs]]
id = "mwEpkwtn_u2BewhHv-hD3"
uri = "file://godsapp-v0.3.1.tar.gz"
type = "unspecified"
title = "GodsApp v0.3.1 — Olympus polish (tarball)"

[[outputs]]
id = "F4ajzMpCFQFDD4YENuwZa"
uri = "file://godsapp-v0.3.1.zip"
type = "unspecified"
title = "GodsApp v0.3.1 — Olympus polish (zip)"

[[outputs]]
id = "pjUFJBzx9R9PNmwcC8B80"
uri = "file://godsapp-v0.3.2.tar.gz"
type = "unspecified"
title = "GodsApp v0.3.2 — baked sky + clouds (tarball)"

[[outputs]]
id = "kVDk9z1trKf4Gh7ta8RjV"
uri = "file://godsapp-v0.3.2.zip"
type = "unspecified"
title = "GodsApp v0.3.2 — baked sky + clouds (zip)"

[[outputs]]
id = "dwen1hWRBw-1OnbnQlrZr"
uri = "file://godsapp-v0.3.3.tar.gz"
type = "unspecified"
title = "GodsApp v0.3.3 — packaging fix + baked sky (tarball)"

[[outputs]]
id = "cyKkoJD9N_oN7HhFYg9Lo"
uri = "file://godsapp-v0.3.3.zip"
type = "unspecified"
title = "GodsApp v0.3.3 — packaging fix + baked sky (zip)"

[[outputs]]
id = "mt0LSe_y_g1TPIXc_ugz9"
uri = "file://godsapp-v0.3.4.tar.gz"
type = "unspecified"
title = "GodsApp v0.3.4 — baked sky + packaging fix + markup fix (tarball)"

[[outputs]]
id = "K_ix391yBu1RZulFAn2jb"
uri = "file://godsapp-v0.3.4.zip"
type = "unspecified"
title = "GodsApp v0.3.4 — baked sky + packaging fix + markup fix (zip)"
